# Meta Data for SEO

## Homepage
title = "SCSC-22F-MLDL"
titleSeparator = "-"
titleAddition = ""
description = ""

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "ko_KR"
domainTLD = "snu-scsc.github.io/22F-MLDL-Intermediate"
titleHome = "SCSC-22F-MLDL"

# ## Twitter Cards
# twitterSite = "@SNU-SCSC"
# twitterCreator = "@SNU-SCSC"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "SNU SCSC"
schemaAuthor = "SCSC"
# schemaAuthorTwitter = "https://twitter.com/SNU-SCSC"
# schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/SNU-SCSC"
schemaLocale = "en-US"
# schemaLogo = "logo/logo_b.png"
schemaLogoWidth = 2791
schemaLogoHeight = 1350
# schemaImage = "logo/default-image.png"
schemaImageWidth = 3509
schemaImageHeight = 2482
# schemaTwitter = "https://twitter.com/SNU-SCSC"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/SNU-SCSC"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"
themeColorDark = "#212529"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.github.com/\">Github</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022-present <a class=\"text-muted\" href=\"https://github.com/SNU-SCSC/\">SNU SCSC</a>"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/SNU-SCSC/22F-MLDL-Intermediate"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["seminar", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = "ALL"
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = true
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true

[social.share]
  facebook = false
  linkedin = false
  twitter = false
  whatsapp = false
  email = false
