name: Hyas CI

on:
  push:
    branches: gh-pages-src
  pull_request:
    branches: gh-pages-src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Hyas project
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm ci

    - name: Run Hyas test script
      run: npm test

    - name: Build production website
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
